// Translation dictionary for common exercise terms and phrases
const translations: Record<string, string> = {
    // Body parts
    "shoulder": "ombro",
    "shoulders": "ombros",
    "hip": "quadril",
    "hips": "quadris",
    "leg": "perna",
    "legs": "pernas",
    "arm": "braço",
    "arms": "braços",
    "chest": "peito",
    "back": "costas",
    "knee": "joelho",
    "knees": "joelhos",
    "elbow": "cotovelo",
    "elbows": "cotovelos",
    "foot": "pé",
    "feet": "pés",
    "hand": "mão",
    "hands": "mãos",
    "wrist": "pulso",
    "wrists": "pulsos",
    "ankle": "tornozelo",
    "ankles": "tornozelos",
    "thigh": "coxa",
    "thighs": "coxas",
    "calf": "panturrilha",
    "calves": "panturrilhas",
    "forearm": "antebraço",
    "forearms": "antebraços",
    "bicep": "bíceps",
    "biceps": "bíceps",
    "tricep": "tríceps",
    "triceps": "tríceps",
    "glute": "glúteo",
    "glutes": "glúteos",
    "hamstring": "posterior de coxa",
    "hamstrings": "posteriores de coxa",
    "quad": "quadríceps",
    "quads": "quadríceps",
    "core": "core",
    "abs": "abdômen",
    "abdominal": "abdominal",
    "neck": "pescoço",
    "spine": "coluna",
    "lower back": "lombar",
    "upper back": "parte superior das costas",

    // Equipment
    "dumbbell": "halter",
    "dumbbells": "halteres",
    "barbell": "barra",
    "bench": "banco",
    "cable": "cabo",
    "machine": "máquina",
    "kettlebell": "kettlebell",
    "band": "faixa elástica",
    "ball": "bola",
    "mat": "tapete",
    "weight": "peso",
    "weights": "pesos",
    "plate": "anilha",
    "plates": "anilhas",

    // Actions
    "sit": "sente-se",
    "stand": "fique de pé",
    "lie": "deite-se",
    "lay": "deite-se",
    "hold": "segure",
    "grab": "pegue",
    "grip": "segure",
    "lift": "levante",
    "raise": "eleve",
    "lower": "abaixe",
    "push": "empurre",
    "pull": "puxe",
    "press": "pressione",
    "squeeze": "contraia",
    "extend": "estenda",
    "flex": "flexione",
    "bend": "dobre",
    "straighten": "estique",
    "rotate": "gire",
    "twist": "torça",
    "curl": "rosqueie",
    "row": "reme",
    "shrug": "encolha",
    "crunch": "contraia",
    "squat": "agache",
    "lunge": "dê uma passada",
    "step": "pise",
    "jump": "pule",
    "lean": "incline-se",
    "tilt": "incline",
    "swing": "balance",
    "drive": "empurre",
    "return": "retorne",
    "bring": "traga",
    "move": "mova",
    "keep": "mantenha",
    "maintain": "mantenha",
    "engage": "ative",
    "contract": "contraia",
    "relax": "relaxe",
    "pause": "pause",
    "repeat": "repita",
    "perform": "execute",
    "complete": "complete",

    // Positions
    "starting position": "posição inicial",
    "position": "posição",
    "upright": "ereto",
    "straight": "reto",
    "neutral": "neutro",
    "forward": "para frente",
    "backward": "para trás",
    "up": "para cima",
    "down": "para baixo",
    "overhead": "acima da cabeça",
    "chest level": "altura do peito",
    "shoulder level": "altura dos ombros",
    "hip level": "altura do quadril",
    "ground": "chão",
    "floor": "chão",
    "ceiling": "teto",
    "side": "lado",
    "sides": "lados",
    "front": "frente",
    "behind": "atrás",
    "above": "acima",
    "below": "abaixo",
    "parallel": "paralelo",
    "perpendicular": "perpendicular",

    // Common phrases
    "with": "com",
    "without": "sem",
    "both": "ambos",
    "each": "cada",
    "one": "um",
    "two": "dois",
    "your": "seu",
    "the": "o",
    "a": "um",
    "an": "um",
    "and": "e",
    "or": "ou",
    "at": "em",
    "on": "em",
    "in": "em",
    "to": "para",
    "from": "de",
    "by": "por",
    "while": "enquanto",
    "until": "até",
    "as": "como",
    "slowly": "lentamente",
    "quickly": "rapidamente",
    "fully": "completamente",
    "slightly": "levemente",
    "gently": "suavemente",
    "firmly": "firmemente",
    "tightly": "firmemente",

    // Instructions
    "start": "comece",
    "begin": "comece",
    "finish": "termine",
    "end": "termine",
    "breathe": "respire",
    "inhale": "inspire",
    "exhale": "expire",
    "focus": "concentre-se",
    "control": "controle",
    "avoid": "evite",
    "ensure": "certifique-se",
    "make sure": "certifique-se",
    "try": "tente",
    "feel": "sinta",
    "throughout": "durante todo",
    "during": "durante",
    "motion": "movimento",
    "movement": "movimento",
    "exercise": "exercício",
    "rep": "repetição",
    "reps": "repetições",
    "set": "série",
    "sets": "séries",
    "range": "amplitude",
    "full range": "amplitude completa",
    "range of motion": "amplitude de movimento",
    "top": "topo",
    "bottom": "base",
    "peak": "pico",
    "apex": "ápice",
    "contraction": "contração",
    "stretch": "alongamento",
    "tension": "tensão",

    // Exercise names and specific terms
    "figure four": "figura quatro",
    "hip thrust": "elevação de quadril",
    "pulldown": "puxada",
    "pull down": "puxada",
    "concentration curl": "rosca concentrada",
    "hammer curl": "rosca martelo",
    "preacher curl": "rosca scott",
    "overhead press": "desenvolvimento",
    "shoulder press": "desenvolvimento de ombros",
    "lateral raise": "elevação lateral",
    "front raise": "elevação frontal",
    "rear delt": "deltoide posterior",
    "fly": "crucifixo",
    "flye": "crucifixo",
    "chest press": "supino",
    "bench press": "supino",
    "incline": "inclinado",
    "decline": "declinado",
    "flat": "reto",
    "seated": "sentado",
    "standing": "em pé",
    "lying": "deitado",
    "prone": "pronado",
    "supine": "supinado",
    "alternating": "alternado",
    "single arm": "braço único",
    "single leg": "perna única",
    "unilateral": "unilateral",
    "bilateral": "bilateral",
    "cross": "cruzado",
    "over": "sobre",
    "blades": "omoplatas",
    "shoulder blades": "omoplatas",
    "palms": "palmas",
    "facing": "voltadas",
    "toward": "em direção a",
    "away from": "afastado de",
    "together": "juntos",
    "apart": "afastados",
    "wide": "ampla",
    "narrow": "estreita",
    "close": "próximo",
    "far": "distante",
};

export function translateInstruction(instruction: string): string {
    if (!instruction) return instruction;

    let translated = instruction;

    // Sort by length (longest first) to avoid partial replacements
    const sortedKeys = Object.keys(translations).sort((a, b) => b.length - a.length);

    for (const key of sortedKeys) {
        // Use word boundaries to avoid replacing parts of words
        const regex = new RegExp(`\\b${key}\\b`, 'gi');
        translated = translated.replace(regex, translations[key]);
    }

    // Capitalize first letter
    if (translated.length > 0) {
        translated = translated.charAt(0).toUpperCase() + translated.slice(1);
    }

    return translated;
}

export function translateInstructions(instructions: string[] | null | undefined): string[] {
    if (!instructions || !Array.isArray(instructions)) {
        return [];
    }
    return instructions.map(translateInstruction);
}
